#!/usr/bin/env python3
#
# Turn a JIS X 0208 BDF font into a compiled-in wsfont(9) header, with a
# Unicode -> glyph table so wsfont_map_unichar() can find the glyphs.
#
#   bdf2wsfont.py NAME font.bdf JIS0208.TXT > NAME.h
#
# Glyphs are stored dense in ku/ten order, (row - 0x21) * 94 + (col - 0x21),
# so the table maps a code point to that index.  The font is 16 pixels wide
# and is meant to sit next to an 8 pixel wide text font: the terminal
# emulator draws it across two cells.

import sys

name, bdf, jis0208 = sys.argv[1:4]
width = height = 16
stride = 2

glyphs = {}
with open(bdf, encoding="latin-1") as f:
    enc = None
    rows = None
    for line in f:
        w = line.split()
        if not w:
            continue
        if w[0] == "ENCODING":
            enc = int(w[1])
        elif w[0] == "BITMAP":
            rows = []
        elif w[0] == "ENDCHAR":
            if enc is not None and rows is not None and len(rows) == height:
                glyphs[enc] = rows
            enc = rows = None
        elif rows is not None:
            rows.append(int(w[0], 16))

def index(jis):
    return (jis // 256 - 0x21) * 94 + (jis % 256 - 0x21)

numchars = 94 * 94

ucs = {}
with open(jis0208, encoding="latin-1") as f:
    for line in f:
        if line.startswith("#"):
            continue
        w = line.split()
        if len(w) < 3:
            continue
        jis, u = int(w[1], 16), int(w[2], 16)
        if u < 0x100 or jis not in glyphs:
            continue
        ucs.setdefault(u, jis)

# The CP932 spellings that UTF-8 text from Windows carries for the
# same characters.
for u, jis in ((0xff5e, 0x2141), (0x2225, 0x2142), (0xff0d, 0x215d),
               (0xffe0, 0x2171), (0xffe1, 0x2172), (0xffe2, 0x224c)):
    if jis in glyphs:
        ucs.setdefault(u, jis)

out = sys.stdout
out.write("/*\n * Generated by bdf2wsfont.py from %s; do not edit.\n */\n\n"
          % bdf.split("/")[-1])
out.write("static u_char %s_data[];\n\n" % name)
out.write("static struct wsdisplay_font %s = {\n" % name)
out.write('\t"%s",\t\t\t/* typeface name */\n' % name)
out.write("\t0,\t\t\t\t/* firstchar */\n")
out.write("\t%d,\t\t\t\t/* numchars */\n" % numchars)
out.write("\tWSDISPLAY_FONTENC_JISX0208,\t/* encoding */\n")
out.write("\t%d,\t\t\t\t/* width */\n" % width)
out.write("\t%d,\t\t\t\t/* height */\n" % height)
out.write("\t%d,\t\t\t\t/* stride */\n" % stride)
out.write("\tWSDISPLAY_FONTORDER_L2R,\t/* bit order */\n")
out.write("\tWSDISPLAY_FONTORDER_L2R,\t/* byte order */\n")
out.write("\t%s_data\t\t\t/* data */\n};\n\n" % name)

out.write("/* Unicode code points and the glyph index for each, sorted. */\n")
out.write("static const uint16_t %s_ucs[] = {" % name)
keys = sorted(ucs)
for i, u in enumerate(keys):
    out.write("\n\t" if i % 8 == 0 else " ")
    out.write("0x%04x," % u)
out.write("\n};\n\n")
out.write("static const uint16_t %s_glyph[] = {" % name)
for i, u in enumerate(keys):
    out.write("\n\t" if i % 8 == 0 else " ")
    out.write("%d," % index(ucs[u]))
out.write("\n};\n\n")
out.write("#define\t%s_NUCS\t%d\n\n" % (name.upper(), len(keys)))

out.write("static u_char %s_data[] = {\n" % name)
for i in range(numchars):
    jis = 0x2121 + (i // 94) * 256 + i % 94
    rows = glyphs.get(jis, [0] * height)
    out.write("\t/* 0x%04x */\n" % jis)
    for r in rows:
        out.write("\t0x%02x, 0x%02x,\n" % (r >> 8, r & 0xff))
out.write("};\n")
